Repository Team-I1lI1I1l-as-barcode/FluffyTime-backend, pull requests merged in 2024-08, with the labels that each got.

#100 게시물 태그 합병
  src/main/java/com/fluffytime/Tag/controller/TagController.java
  src/main/java/com/fluffytime/Tag/controller/api/TagPostRestController.java
  src/main/java/com/fluffytime/Tag/controller/api/TagRestController.java
  src/main/java/com/fluffytime/Tag/dto/request/TagRequest.java
  src/main/java/com/fluffytime/Tag/dto/response/TagResponse.java
  src/main/java/com/fluffytime/Tag/service/TagPostService.java
  src/main/java/com/fluffytime/Tag/service/TagService.java
  src/main/java/com/fluffytime/config/SecurityConfig.java
  src/main/java/com/fluffytime/domain/Post.java
  src/main/java/com/fluffytime/domain/PostImages.java
  src/main/java/com/fluffytime/login/jwt/util/JwtTokenizer.java
  src/main/java/com/fluffytime/post/controller/api/PostRestController.java
  src/main/java/com/fluffytime/post/dto/request/PostRequest.java
  src/main/java/com/fluffytime/post/dto/response/ApiResponse.java
  src/main/java/com/fluffytime/post/dto/response/PostResponse.java
  src/main/java/com/fluffytime/post/dto/response/PostResponseCode.java
  src/main/java/com/fluffytime/post/exception/ContentLengthExceeded.java
  src/main/java/com/fluffytime/post/exception/FileSizeExceeded.java
  src/main/java/com/fluffytime/post/exception/FileUploadFailed.java
  src/main/java/com/fluffytime/post/exception/PostErrorCode.java
  src/main/java/com/fluffytime/post/exception/PostNotInTempStatus.java
  src/main/java/com/fluffytime/post/exception/TooManyFiles.java
  src/main/java/com/fluffytime/post/exception/UnsupportedFileFormat.java
  src/main/java/com/fluffytime/post/service/PostService.java
  src/main/java/com/fluffytime/repository/PostImagesRepository.java
  src/main/java/com/fluffytime/repository/TagPostRepository.java
  src/main/java/com/fluffytime/repository/TagRepository.java
  src/main/resources/static/css/post/createPost.css
  src/main/resources/static/html/post/createPost.html
  src/main/resources/static/js/post/createPost.js
  src/main/resources/static/js/post/postDetail.js
Labels: enhancement

#224 🎨 Fix: 게시물 상세보기 수정
  src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
  src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
  src/main/java/com/fluffytime/domain/board/entity/Post.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/resources/static/css/post/postDetail.css
  src/main/resources/static/js/post/createPost.js
  src/main/resources/static/js/post/postDetail.js
  src/main/resources/templates/common/tempModal.html
  src/main/resources/templates/post/postDetail.html
Labels: ⚡️perf

#223 Feature/태그
  src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
  src/main/java/com/fluffytime/domain/board/dto/request/PostRequest.java
  src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
  src/main/java/com/fluffytime/domain/board/entity/Tag.java
  src/main/java/com/fluffytime/domain/board/entity/TagPost.java
  src/main/java/com/fluffytime/domain/board/repository/TagPostRepository.java
  src/main/java/com/fluffytime/domain/board/repository/TagRepository.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/domain/board/service/TagService.java
  src/main/java/com/fluffytime/domain/board/validation/annotation/ValidTags.java
  src/main/java/com/fluffytime/domain/board/validation/validator/TagsValidator.java
  src/main/java/com/fluffytime/domain/user/controller/api/UserRestController.java
  src/main/resources/static/css/post/createPost.css
  src/main/resources/static/js/post/createPost.js
  src/main/resources/templates/common/createModal.html
Labels: ✨feat

#226 🐛 Fix: 임시저장 게시물 목록 & 이어쓰기 모달 깨짐 현상을 수정하였습니다.
  src/main/resources/static/css/post/createPost.css
  src/main/resources/static/js/post/createPost.js
Labels: 🐛bug

#229 💄 Style: 게시물 상세보기 관련 UI 수정
  src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
  src/main/java/com/fluffytime/domain/board/repository/TagPostRepository.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/domain/board/service/TagService.java
  src/main/resources/static/css/comment/comment.css
  src/main/resources/static/css/post/postDetail.css
  src/main/resources/static/js/post/createPost.js
  src/main/resources/static/js/post/postDetail.js
  src/main/resources/templates/post/postDetail.html
Labels: 💄 Style

#230 🎨 Fix : 임시저장 글 목록 관련 수정
  src/main/java/com/fluffytime/domain/board/controller/PostController.java
  src/main/java/com/fluffytime/domain/board/repository/PostRepository.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
Labels: ⚡️perf

#233 ✨ Feat: 게시글 수정 시 태그 수정 로직 구현
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/domain/board/service/TagService.java
  src/main/resources/static/css/post/PostEdit.css
  src/main/resources/static/js/post/postDetail.js
  src/main/resources/static/js/post/postEdit.js
  src/main/resources/templates/post/postEdit.html
Labels: ✨feat

#239 🔥 Remove: 불필요한 log 제거
  src/main/java/com/fluffytime/domain/admin/interceptor/AdminCheckInterceptor.java
  src/main/java/com/fluffytime/domain/user/service/LoginService.java
  src/main/java/com/fluffytime/global/auth/jwt/dto/CustomUserDetails.java
  src/main/java/com/fluffytime/global/auth/jwt/filter/JwtAuthenticationFilter.java
Labels: ♻️refactor

#243 🐛 Fix: 임시저장 관련 수정
  src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/global/config/aws/S3Service.java
  src/main/resources/static/js/post/createPost.js
Labels: 🐛bug

#245 ✨ Feat: 관리자 페이지 구현 - 통계
  src/main/java/com/fluffytime/domain/admin/controller/AdminController.java
  src/main/java/com/fluffytime/domain/admin/controller/api/StatisticsRestController.java
  src/main/java/com/fluffytime/domain/admin/dto/DailyContentsCount.java
  src/main/java/com/fluffytime/domain/admin/dto/DailyCount.java
  src/main/java/com/fluffytime/domain/admin/dto/DailyUserCount.java
  src/main/java/com/fluffytime/domain/admin/dto/response/DailyCountStatisticsResponse.java
  src/main/java/com/fluffytime/domain/admin/service/PostStatisticsService.java
  src/main/java/com/fluffytime/domain/admin/service/UserStatisticsService.java
  src/main/java/com/fluffytime/domain/admin/util/convertor/StatisticsConvertor.java
  src/main/java/com/fluffytime/domain/board/repository/PostRepository.java
  src/main/java/com/fluffytime/domain/user/repository/UserRepository.java
  src/main/java/com/fluffytime/global/config/SecurityConfig.java
  src/main/resources/static/css/admin/common/adminStyles.css
  src/main/resources/static/css/admin/common/sidebar.css
  src/main/resources/static/css/admin/statistics/statistics.css
  src/main/resources/static/css/admin/user/userManagementPage.css
  src/main/resources/static/js/admin/statistics/user.js
  src/main/resources/static/js/auth/adminCheck.js
  src/main/resources/templates/admin/admin.html
  src/main/resources/templates/admin/common/sidebar.html
  src/main/resources/templates/admin/user/userManagementPage.html
Labels: ✨feat
