Repository Team-I1lI1I1l-as-barcode/FluffyTime-backend, pull requests merged in 2024-09, with the labels that each got.

#246 ✨ Feat: 다른 사람에게 좋아요 수 숨기기 기능 구현
  src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
  src/main/java/com/fluffytime/domain/board/dto/request/PostRequest.java
  src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
  src/main/java/com/fluffytime/domain/board/entity/Post.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/resources/static/css/post/postDetail.css
  src/main/resources/static/js/post/createPost.js
  src/main/resources/static/js/post/postDetail.js
  src/main/resources/static/js/post/postEdit.js
  src/main/resources/templates/common/createModal.html
  src/main/resources/templates/post/postDetail.html
  src/main/resources/templates/post/postEdit.html
Labels: ✨feat

#249 ✨ Feat: 릴스 기능 구현
  src/main/java/com/fluffytime/domain/board/controller/ReelsController.java
  src/main/java/com/fluffytime/domain/board/controller/api/ReelsRestController.java
  src/main/java/com/fluffytime/domain/board/dto/response/ReelsResponse.java
  src/main/java/com/fluffytime/domain/board/entity/Reels.java
  src/main/java/com/fluffytime/domain/board/repository/ReelsRepository.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/domain/board/service/ReelsService.java
  src/main/resources/static/css/post/reels.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/post/reels.js
  src/main/resources/templates/common/sidebar.html
  src/main/resources/templates/post/reels.html
Labels: ✨feat

#251 🐛 Fix: post 엔티티 수정
  src/main/java/com/fluffytime/domain/board/dto/request/PostRequest.java
  src/main/java/com/fluffytime/domain/board/entity/Post.java
Labels: 🐛bug

#253 Feature/관리자
  src/main/java/com/fluffytime/domain/admin/controller/api/UserManagementRestController.java
  src/main/java/com/fluffytime/domain/admin/dto/response/UserInfoResponse.java
  src/main/java/com/fluffytime/domain/admin/service/UserManagementService.java
  src/main/java/com/fluffytime/domain/board/entity/Post.java
  src/main/java/com/fluffytime/domain/board/service/CommentLikeService.java
  src/main/java/com/fluffytime/domain/board/service/CommentService.java
  src/main/java/com/fluffytime/domain/board/service/PostLikeService.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/domain/board/service/ReplyLikeService.java
  src/main/java/com/fluffytime/domain/board/service/ReplyService.java
  src/main/java/com/fluffytime/domain/notification/controller/api/AdminNotificationRestController.java
  src/main/java/com/fluffytime/domain/notification/controller/api/NotificationRestController.java
  src/main/java/com/fluffytime/domain/notification/dto/response/AdminNotificationResponse.java
  src/main/java/com/fluffytime/domain/notification/entity/AdminNotification.java
  src/main/java/com/fluffytime/domain/notification/entity/enums/AdminNotificationType.java
  src/main/java/com/fluffytime/domain/notification/repository/AdminNotificationRepository.java
  src/main/java/com/fluffytime/domain/notification/service/AdminNotificationService.java
  src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
  src/main/java/com/fluffytime/domain/notification/service/SseEmitters.java
  src/main/java/com/fluffytime/domain/search/controller/api/ExploreRestController.java
  src/main/java/com/fluffytime/domain/search/controller/api/SearchRestController.java
  src/main/java/com/fluffytime/domain/user/repository/UserRepository.java
  src/main/java/com/fluffytime/domain/user/service/JoinService.java
  src/main/java/com/fluffytime/domain/user/service/LoginService.java
  src/main/java/com/fluffytime/domain/user/service/MyPageService.java
  src/main/java/com/fluffytime/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/css/admin/common/adminStyles.css
  src/main/resources/static/css/admin/statistics/statistics.css
  src/main/resources/static/js/admin/statistics/notification.js
  src/main/resources/static/js/admin/statistics/user.js
  src/main/resources/static/js/admin/usermanagement/paging.js
  src/main/resources/templates/admin/admin.html
  src/main/resources/templates/admin/user/userManagementPage.html
  src/main/resources/templates/notification/notificationView.html
Labels: ✨feat

#256 Feature/관리자
  src/main/java/com/fluffytime/domain/admin/controller/api/UserManagementRestController.java
  src/main/java/com/fluffytime/domain/admin/dto/response/UserInfoResponse.java
  src/main/java/com/fluffytime/domain/board/service/CommentService.java
  src/main/java/com/fluffytime/domain/board/service/ReelsService.java
  src/main/java/com/fluffytime/domain/board/service/ReplyService.java
  src/main/java/com/fluffytime/domain/chat/service/ChatServcie.java
  src/main/java/com/fluffytime/domain/notification/service/NotificationService.java
  src/main/java/com/fluffytime/domain/user/service/LoginService.java
  src/main/resources/static/css/admin/statistics/statistics.css
  src/main/resources/templates/admin/common/sidebar.html
Labels: 🐛bug

#259 🐛 Fix: 릴스 엔티티 수정
  src/main/java/com/fluffytime/domain/board/controller/ReelsController.java
  src/main/java/com/fluffytime/domain/board/controller/api/ReelsRestController.java
  src/main/java/com/fluffytime/domain/board/dto/response/PostResponse.java
  src/main/java/com/fluffytime/domain/board/dto/response/ReelsResponse.java
  src/main/java/com/fluffytime/domain/board/entity/Post.java
  src/main/java/com/fluffytime/domain/board/entity/PostImages.java
  src/main/java/com/fluffytime/domain/board/entity/Reels.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/domain/board/service/ReelsService.java
  src/main/resources/static/css/post/reels.css
  src/main/resources/static/js/post/reels.js
  src/main/resources/templates/common/sidebar.html
  src/main/resources/templates/post/reels.html
Labels: 🐛bug

#260 🚑️ Hotfix: 동영상 엑스박스 표시 문제 해결
  src/main/java/com/fluffytime/domain/board/service/ReelsService.java
  src/main/resources/static/css/home/home.css
  src/main/resources/static/js/explore/explore.js
  src/main/resources/static/js/home/home.js
  src/main/resources/templates/post/reels.html
Labels: 🐛bug

#263 Refactor: 메서드 주석 정리 및 도메인 경로 적용
  src/main/java/com/fluffytime/domain/admin/controller/AdminController.java
  src/main/java/com/fluffytime/domain/admin/controller/api/StatisticsRestController.java
  src/main/java/com/fluffytime/domain/admin/controller/api/UserManagementRestController.java
  src/main/java/com/fluffytime/domain/admin/interceptor/AdminCheckInterceptor.java
  src/main/java/com/fluffytime/domain/admin/service/PostStatisticsService.java
  src/main/java/com/fluffytime/domain/admin/service/UserManagementService.java
  src/main/java/com/fluffytime/domain/admin/service/UserStatisticsService.java
  src/main/java/com/fluffytime/domain/admin/util/constants/StatisticsDateRange.java
  src/main/java/com/fluffytime/domain/admin/util/convertor/StatisticsConvertor.java
  src/main/java/com/fluffytime/domain/user/controller/UserController.java
  src/main/java/com/fluffytime/domain/user/controller/api/UserRestController.java
  src/main/java/com/fluffytime/domain/user/dao/EmailCertificationDao.java
  src/main/java/com/fluffytime/domain/user/dao/PasswordChangeDao.java
  src/main/java/com/fluffytime/domain/user/interceptor/LoginCheckInterceptor.java
  src/main/java/com/fluffytime/domain/user/service/JoinService.java
  src/main/java/com/fluffytime/domain/user/service/LoginService.java
  src/main/java/com/fluffytime/global/auth/jwt/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/fluffytime/global/auth/jwt/exception/JwtErrorCode.java
  src/main/java/com/fluffytime/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/fluffytime/global/auth/jwt/util/JwtResponseProvider.java
  src/main/java/com/fluffytime/global/auth/jwt/util/JwtTokenizer.java
  src/main/java/com/fluffytime/global/auth/jwt/util/TokenCookieManager.java
  src/main/java/com/fluffytime/global/auth/oauth2/handler/CustomSuccessHandler.java
  src/main/java/com/fluffytime/global/common/exception/GlobalExceptionHandler.java
  src/main/java/com/fluffytime/global/common/smtp/builder/CertificationEmailContent.java
  src/main/java/com/fluffytime/global/common/smtp/builder/ChangePasswordEmailContent.java
  src/main/java/com/fluffytime/global/common/smtp/service/EmailService.java
  src/main/resources/application.yml
  src/main/resources/static/css/admin/common/adminStyles.css
  src/main/resources/static/css/admin/common/sidebar.css
  src/main/resources/static/css/admin/statistics/statistics.css
  src/main/resources/static/css/join/EmailCertificationResult.css
  src/main/resources/static/css/join/join.css
  src/main/resources/static/css/join/joinResult.css
  src/main/resources/static/css/join/socialJoin.css
  src/main/resources/static/css/login/changePassword.css
  src/main/resources/static/css/login/findEmail.css
  src/main/resources/static/css/login/findPassword.css
  src/main/resources/static/css/login/login.css
  src/main/resources/static/js/admin/statistics/notification.js
  src/main/resources/static/js/admin/usermanagement/paging.js
  src/main/resources/static/js/auth/auth.js
  src/main/resources/static/js/join/certificate.js
  src/main/resources/static/js/join/completeCertification.js
  src/main/resources/static/js/join/join.js
  src/main/resources/static/js/join/socialJoin.js
  src/main/resources/static/js/login/changePassword.js
  src/main/resources/static/js/login/login.js
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/explore/explore.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage/mypage.html
  src/main/resources/templates/mypage/profiles/profile.html
  src/main/resources/templates/notification/notificationView.html
  src/main/resources/templates/post/reels.html
  src/main/resources/templates/search/search.html
  src/main/resources/templates/userpage/userpage.html
Labels: 🐛bug, ⚙️config, ♻️refactor

#265 🐛 Fix: 릴스 수정
  src/main/java/com/fluffytime/domain/board/controller/FileUploadController.java
  src/main/java/com/fluffytime/domain/board/entity/Reels.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/resources/static/css/post/postEdit.css
  src/main/resources/static/css/post/reels.css
  src/main/resources/static/js/post/reels.js
  src/main/resources/templates/post/reels.html
Labels: 🐛bug

#268 🐛 Fix: 도메인 경로 수정 & 릴스 css 수정
  src/main/java/com/fluffytime/global/common/smtp/builder/CertificationEmailContent.java
  src/main/java/com/fluffytime/global/common/smtp/builder/ChangePasswordEmailContent.java
  src/main/resources/application.yml
  src/main/resources/static/css/post/reels.css
Labels: 🐛bug

#270 🐛 Fix: 로그아웃 js 리다이렉션 제거
  src/main/resources/static/js/common/logout.js
Labels: 🐛bug

#272 🚑️ Hotfix: 로그아웃 리디렉션 문제 수정
  src/main/java/com/fluffytime/domain/user/service/LoginService.java
  src/main/resources/static/js/common/logout.js
Labels: 🐛bug

#273 Hotfix: 관리자 알림 js 경로 수정
  src/main/resources/static/js/admin/statistics/notification.js
  src/main/resources/static/js/auth/auth.js
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/main.html
Labels: 🐛bug

#275 ♻️ Refactor: StatisticsRestController Http Method 변경
  src/main/java/com/fluffytime/domain/admin/controller/api/StatisticsRestController.java
  src/main/java/com/fluffytime/domain/notification/service/SseEmitters.java
  src/main/resources/static/js/admin/statistics/user.js
Labels: ♻️refactor

#277 ✨ Feat: 릴스에 좋아요 기능 추가
  src/main/resources/static/css/post/reels.css
  src/main/resources/static/js/post/reels.js
Labels: ✨feat

#279 🐛 Fix: reels 좋아요, 북마크 버튼 작동 안함 수정
  src/main/java/com/fluffytime/domain/chat/service/ChatServcie.java
  src/main/java/com/fluffytime/global/config/SecurityConfig.java
  src/main/resources/static/css/post/reels.css
  src/main/resources/static/js/notification/notification.js
  src/main/resources/static/js/post/reels.js
Labels: 🐛bug

#284 FluffyTIme v2.0 doc 추가
  README.md
  build.gradle
  images/DMPage.png
  images/ERD.png
  images/adminPage-statistics.png
  images/architecture.png
  images/createPost.png
  images/createpost.png
  images/detailpost.png
  images/explore.png
  images/explorePage.png
  images/followerPageList.png
  images/home-admin.png
  images/home-user.png
  images/home.png
  images/join.png
  images/joinPage.png
  images/likeLlstPage.png
  images/login.png
  images/loginPage.png
  images/myPage.png
  images/mypage.png
  images/notificationPage.png
  images/postDetailPage.png
  images/postEditPage.png
  images/profile.png
  images/profileEditPage.png
  images/reelsPage.png
  images/search.png
  images/searchEamilPage.png
  images/searchPage.png
  images/searchPasswordPage.png
  images/tempPostListPage.png
  images/userPage.png
  images/userpage.png
  src/main/resources/static/js/home/home.js
  src/main/resources/static/js/mypage/mypage.js
  src/main/resources/static/js/mypage/profiles/profile.js
  src/main/resources/static/js/userpage/userpage.js
  text
Labels: 📝docs

#291 ♻️ Refactor: 메소드 분리
  src/main/java/com/fluffytime/domain/board/controller/api/PostRestController.java
  src/main/java/com/fluffytime/domain/board/service/PostService.java
  src/main/java/com/fluffytime/domain/board/service/ReelsService.java
Labels: ♻️refactor
